/* Contenu indépendant du moteur. Questions originales, jamais présentées comme annales. */
window.LAB_CONTENT = (() => {
 const sources = {
 concours:{label:'Ministère de l’Économie — concours C externe',url:'https://www.economie.gouv.fr/rejoignez-nous/agent-administratif-principal-des-finances-publiques-de-2eme-classe-externe-dgfip'},
 missions:{label:'DGFiP — nos missions',url:'https://www.economie.gouv.fr/dgfip/comprendre-la-dgfip/nos-missions'}
 };
 const topics=['Mathématiques','Logique','DGFiP','Numérique','Histoire','Géographie','EMC','Ministères économiques et financiers','Actualité économique','Actualité sociale','Actualité internationale'];
 const raw=[
 ['math-01','Mathématiques','Pourcentages','Combien représentent 15 % de 240 ?', '36','240 × 15 ÷ 100 = 36. Décomposer : 10 % = 24 et 5 % = 12.','10 % + 5 % : une grande marche, puis une demi-marche.',['24','36','40','48'],1],
 ['math-02','Mathématiques','Évolution relative','Un prix passe de 80 à 100 €. Quelle est la hausse en pourcentage ?','25 %','La hausse est de 20 €. On la rapporte au prix initial : 20 ÷ 80 × 100 = 25 %.','Toujours revenir au point de départ.',['20 %','25 %','80 %','125 %'],1],
 ['math-03','Mathématiques','Proportionnalité','Trois dossiers prennent 12 minutes. Au même rythme, combien de temps prennent cinq dossiers ?','20 minutes','12 ÷ 3 = 4 minutes par dossier ; 5 × 4 = 20 minutes.','Passer par un, puis multiplier.',['15 minutes','18 minutes','20 minutes','24 minutes'],2],
 ['math-04','Mathématiques','Moyenne','Quelle est la moyenne de 8, 12 et 16 ?','12','Additionner les valeurs (36), puis diviser par leur nombre (3).','Somme / nombre.',['10','12','14','18'],1],
 ['math-05','Mathématiques','Fractions','Combien vaut 1/2 + 1/4 ?','3/4','1/2 = 2/4. Donc 2/4 + 1/4 = 3/4.','Découper toutes les parts à la même taille.',['2/6','1/8','3/4','2/4'],2],
 ['logic-01','Logique','Suite multiplicative','Compléter : 3, 6, 12, 24, …','48','Chaque terme est multiplié par 2.','Un escalier qui double à chaque marche.',['30','36','48','60'],2],
 ['logic-02','Logique','Déduction','Tous les dossiers rouges sont urgents. Le dossier A est rouge. Que peut-on conclure ?','A est urgent','La règle concerne tous les dossiers rouges, donc elle s’applique à A. On ne peut pas inverser la règle.','Rouge → urgent ; pas forcément l’inverse.',['A est urgent','Tous les urgents sont rouges','A est clos','On ne peut rien conclure'],0],
 ['logic-03','Logique','Suite de différences','Compléter : 2, 5, 9, 14, …','20','Les écarts sont +3, +4, +5, puis +6.','Regarder les marches entre les nombres.',['18','19','20','21'],2],
 ['dg-01','DGFiP','Deux familles de missions','Quelles sont les deux grandes familles de missions de la DGFiP ?','Fiscalité et gestion publique','La DGFiP intervient dans le domaine fiscal et dans la gestion des finances publiques.','Deux ailes dans le palais : impôts et comptes publics.',['Fiscalité et gestion publique','Justice et défense','Santé et enseignement','Diplomatie et transports'],0,'missions'],
 ['dg-02','DGFiP','Chaîne fiscale','Quels trois mots relient la base de l’impôt, sa vérification et son encaissement ?','Assiette, contrôle, recouvrement','L’assiette désigne la base du calcul ; le contrôle vérifie ; le recouvrement concerne la perception des sommes dues.','Une assiette géante, une loupe, puis un coffre : A-C-R.',['Assiette, contrôle, recouvrement','Vote, jugement, sanction','Budget, élection, justice','Accueil, tri, archivage'],0,'missions'],
 ['dg-03','DGFiP','Comptes publics','La qualité des comptes de l’État relève-t-elle des missions de la DGFiP ?','Oui','La DGFiP contrôle la production et la qualité des comptes de l’État.','Un grand livre de comptes sous une lampe.',['Oui','Non, uniquement les impôts','Uniquement les comptes privés','Uniquement les comptes européens'],0,'missions'],
 ['dg-04','DGFiP','Origine de la DGFiP','Quelles directions ont fusionné pour créer la DGFiP en 2008 ?','Impôts et Comptabilité publique','La DGFiP résulte de la fusion de la Direction générale des Impôts et de la Direction générale de la Comptabilité publique.','Deux portes deviennent une en 2008.',['Impôts et Comptabilité publique','Douanes et Trésor','Budget et INSEE','Justice et Impôts'],0,'missions'],
 ['num-01','Numérique','Hameçonnage','Un courriel inattendu demande votre mot de passe. Quel réflexe adopter ?','Ne pas le communiquer et vérifier par un canal connu','Ne pas utiliser le lien du message pour vérifier son authenticité. Rejoindre le service par son adresse connue.','Un hameçon dans une enveloppe : faire une pause.',['Répondre avec le mot de passe','Cliquer pour vérifier','Ne pas le communiquer et vérifier par un canal connu','Transférer ses identifiants'],2],
 ['num-02','Numérique','Tableur','Quelle formule additionne les cellules A1 à A5 dans un tableur en français ?','=SOMME(A1:A5)','Le deux-points décrit une plage continue. Cette syntaxe est celle des tableurs courants en français.','Deux points relient les deux bouts.',['=A1+A5','=SOMME(A1:A5)','=TOTAL(A1-A5)','=A1:A5'],1],
 ['num-03','Numérique','Sauvegarde','Une copie unique sur le même ordinateur suffit-elle à se protéger de sa panne ?','Non','Une panne du support peut détruire les deux fichiers. Une sauvegarde doit aussi exister sur un support distinct.','Deux paniers, pas deux œufs dans le même panier.',['Oui','Non','Seulement si le nom change','Seulement dans un autre dossier'],1]
 ];
 const notions=raw.map(([id,category,title,question,answer,explanation,mnemonic,choices,correct,source])=>({id,category,title,question,answer,explanation,mnemonic,choices,correct,source,updated:'2026-09-23',status:source?'Vérifié sur source officielle':'Exercice original · connaissance stable',difficulty:1}));
 const rooms=[{id:'missions',title:'La salle des missions',subtitle:'Un parcours en trois repères pour reconstruire la chaîne fiscale.',objects:[{icon:'🍽️',label:'L’assiette géante',id:'dg-02',association:'À gauche, une assiette porte la base du calcul de l’impôt.'},{icon:'🔎',label:'La loupe',id:'dg-02',association:'Au centre, une loupe vérifie la déclaration : le contrôle.'},{icon:'🧰',label:'Le coffre',id:'dg-02',association:'À droite, le coffre reçoit les sommes dues : le recouvrement.'},{icon:'📖',label:'Le grand livre',id:'dg-03',association:'Au fond, le livre rappelle la qualité des comptes de l’État.'}]}];
 const practice={title:'Organiser un accueil sur rendez-vous',context:'Dossier fictif — service public imaginaire. Le responsable demande un courriel de 120 à 180 mots aux agents : rappeler le problème, annoncer l’organisation et indiquer les points de vigilance. N’inventez aucune donnée.',cards:[{text:'Note du responsable : le nouveau dispositif commence le 12 octobre.',group:'Organisation',priority:'Essentiel'},{text:'Bilan : 40 % des visites portent sur une démarche réalisable en ligne.',group:'Constat',priority:'Essentiel'},{text:'Planning : deux agents assurent les rendez-vous le matin.',group:'Organisation',priority:'Essentiel'},{text:'Consigne : maintenir un accueil pour les situations urgentes.',group:'Vigilance',priority:'Essentiel'},{text:'Consigne : proposer un accompagnement aux personnes éloignées du numérique.',group:'Vigilance',priority:'Essentiel'},{text:'Le mobilier du hall a été changé l’année dernière.',group:'Hors sujet',priority:'Secondaire'}],correction:'Objet : organisation de l’accueil à compter du 12 octobre\n\nBonjour,\n\nLe bilan montre que 40 % des visites concernent une démarche réalisable en ligne. Afin de mieux orienter les usagers, un nouveau dispositif d’accueil sur rendez-vous sera mis en place le 12 octobre.\n\nDeux agents assureront les rendez-vous le matin. Nous devrons veiller à expliquer cette organisation aux usagers et à les orienter selon leur besoin. Les situations urgentes continueront à bénéficier d’un accueil. Les personnes éloignées du numérique devront pouvoir recevoir un accompagnement ; la possibilité d’effectuer une démarche en ligne ne doit pas conduire à les laisser sans aide.\n\nMerci de porter une attention particulière à ces deux points de vigilance lors de la mise en place du dispositif. L’objectif est de concilier une meilleure organisation de l’accueil avec une réponse adaptée aux besoins des usagers.\n\nCordialement'};
 return {sources,topics,notions,rooms,practice,examDate:'2026-09-29'};
})();
