/* Atelier de méthode : progression de travail dans drafts, sans changer les notions. */
const MethodRules={budget(values,total=180){const valid=Array.isArray(values)&&values.length===7&&values.every(v=>Number.isInteger(v)&&v>=0&&v<=total);const sum=valid?values.reduce((a,b)=>a+b,0):0;return {valid:valid&&sum===total&&values[6]>0,sum,remaining:total-sum};}};
if(typeof module!=='undefined')module.exports=MethodRules;
let methodMobilePanel="work",methodItem=0,methodCorrection=false,methodRecall=false,methodFlips=new Set();
const methodData=()=>window.METHOD_CONTENT;
const methodStep=()=>Math.min(6,Math.max(0,Math.trunc(Number(state.drafts['method-step']))||0));
const methodValue=(key,fallback='')=>state.drafts['method-'+key]??fallback;
function methodField(key,label,fallback=''){return `<label for="method-${key}">${esc(label)}</label><textarea id="method-${key}" data-draft="method-${key}">${esc(methodValue(key,fallback))}</textarea>`;}
function methodSelect(key,label,options){return `<label for="method-${key}">${esc(label)}</label><select id="method-${key}" data-draft="method-${key}"><option value="">Choisir…</option>${options.map(v=>`<option ${methodValue(key)===v?'selected':''}>${esc(v)}</option>`).join('')}</select>`;}
function methodView(){
 const d=methodData(),i=methodStep(),s=d.steps[i],free=methodValue('mode')==='free';
 const panels=methodPanels(i);
 return heading('Méthode · conseils pédagogiques','Comment aborder le cas pratique',s.goal)+
 `<div class="row between">${btn('← Revenir à mon dossier','method-return')}<div class="row">${btn('Découvrir la méthode','method-mode','data-mode="guided" aria-pressed="'+!free+'"',!free?'selected':'')}${btn('M’entraîner sans aide','method-mode','data-mode="free" aria-pressed="'+free+'"',free?'selected':'')}</div></div>
 <nav class="method-steps" aria-label="Étapes méthodologiques">${d.steps.map((s,j)=>btn(`${j+1} ${s.icon} ${s.title}`,'method-step',`data-index="${j}" ${i===j?'aria-current="step"':''}`)).join('')}</nav>
 <details class="method-official"><summary>Cadre officiel vérifié · conseils et exercice à distinguer</summary><p>${d.official}</p><p><a href="${C.sources.concours.url}" target="_blank" rel="noopener">Modalités officielles ↗</a> · <a href="${C.sources.zeroCase.url}" target="_blank" rel="noopener">Sujet zéro 2026 ↗</a> · vérifiés le ${d.verifiedAt}</p><p>Les exercices ci-dessous sont fictifs. Les méthodes et temps proposés sont des conseils. Les couleurs de l’interface ne sont pas des consignes de mise en forme de la copie.</p></details>
 <div class="method-panel-switch" role="group" aria-label="Panneau de travail">${[["source","Document"],["work","Exercice"],["help","Aide / correction"]].map(([key,label])=>btn(label,"method-panel",`data-panel="${key}" aria-pressed="${methodMobilePanel===key}"`)).join("")}</div><div class="method-desk" data-mobile-panel="${methodMobilePanel}"><section class="card method-source"><span class="eyebrow">${i===5?'Repères de décision':'Document / commande'}</span>${panels.source}</section><section class="card method-work"><span class="eyebrow">${s.icon} ${s.title} · essayer</span>${panels.work}<p id="method-feedback" role="status"></p></section><section class="card method-help"><span class="eyebrow">Méthode / comparaison</span>${free?`<details><summary>Un indice à la demande</summary><p>${esc(s.tip)}</p></details>`:`<p>${esc(s.tip)}</p>`}<div id="method-correction">${methodCorrection||i>=5?panels.correction:'<p class="muted">La proposition apparaît après votre tentative.</p>'}</div></section></div>
 <div class="row between method-bottom">${btn('← Étape précédente','method-prev',i===0?'disabled':'')}<span>${i+1} / 7 · brouillons sauvegardés</span>${btn(i===6?'Retour à mon dossier':'Étape suivante →',i===6?'method-return':'method-next','','primary')}</div>
 <details class="method-recall"><summary>🧠 Fermer la méthode et la retrouver de mémoire</summary><p>${s.recall}</p>${methodField('recall-'+i,'Votre réponse, sans relire')}${btn('Vérifier mon rappel','method-recall')}<div id="method-recall-answer">${methodRecall?`<p class="feedback">${s.answer}</p>`:''}</div></details>`;
}
function methodDocs(){return methodData().documents.map(doc=>`<details ${doc.id==='D1'?'open':''}><summary>${doc.id} · ${doc.title}</summary><small>${doc.author} · ${doc.date}</small><p>${doc.text}</p></details>`).join('');}
function methodItemNav(count){return `<div class="row between">${btn('← Carte','method-item-prev',methodItem===0?'disabled':'')}<small>${methodItem+1}/${count}</small>${btn('Carte →','method-item-next',methodItem===count-1?'disabled':'')}</div>`;}
function methodPanels(i){
 const d=methodData(),check=btn('Comparer ma tentative','method-check','','primary');
 if(i===0){const c=d.command[methodItem];return {source:`<h2>Une commande fictive</h2><p>Pour comprendre la commande entière, ouvrez puis classez ses six passages.</p><details><summary>Lire la commande complète</summary><p>${d.command.map(c=>esc(c[0])).join(' ')}</p></details>`,work:`${methodItemNav(6)}<blockquote class="command-fragment">${c[0]}</blockquote>${methodSelect('command-'+methodItem,'À quoi correspond ce passage ?',d.command.map(c=>c[1]))}${check}`,correction:`<div class="feedback"><strong>${c[1]}</strong><p>${c[2]}</p></div>`};}
 if(i===1){const e=d.extracts[methodItem];return {source:`<h2>Trois documents</h2>${methodDocs()}`,work:`${methodItemNav(5)}<h2>${e.text}</h2>${methodSelect('extract-doc-'+methodItem,'Document d’origine',['D1','D2','D3','Aucun'])}${methodSelect('extract-kind-'+methodItem,'Nature',['Fait','Exemple','Chiffre','Consigne','Interprétation'])}${methodSelect('extract-theme-'+methodItem,'Utilité',['Constat','Organisation','Vigilance','Écarter'])}${methodField('extract-note-'+methodItem,'Votre note courte (facultatif)')}${check}`,correction:`<div class="feedback"><strong>${e.doc} · ${e.kind} · ${e.theme}</strong><p>${e.why}</p></div><p>Gardez la référence de source dans votre brouillon pour retrouver le fait.</p>`};}
 if(i===2)return {source:`<h2>Deux axes imposés ici</h2><p>Constat → organisation et vigilances.</p><details><summary>D’autres structures, selon la commande</summary>${d.planPatterns.map(([title,why])=>`<h3>${title}</h3><p>${why}</p>`).join('')}</details><details><summary>Comparer un mauvais plan</summary><p>« I. Historique du logo ; II. Toute l’organisation » : le premier axe est hors sujet et le second concentre tout. Ici, « I. Constat ; II. Organisation et vigilances » répond à la demande.</p></details>`,work:`<div class="plan-board">${d.planCards.map(([text],j)=>`<article class="method-chip"><p>${text}</p>${methodSelect('plan-card-'+j,'Placer la carte '+(j+1),['Constat','Organisation et vigilances','Écarter'])}</article>`).join('')}</div>${methodField('plan-titles','Nommez vos deux parties')}${check}`,correction:`<div class="feedback">${d.planCards.map(([t,g],j)=>`<p>${j+1}. ${g} : ${t}</p>`).join('')}</div><p>Le constat justifie la suite ; les modalités et vigilances répondent à la seconde partie. Le logo est écarté. Plusieurs formulations de titres sont possibles.</p>`};
 if(i===3){const r=d.rewrites[methodItem];return {source:`<h2>Un texte utile, sans ajout</h2>${methodDocs()}<details><summary>Architecture possible de la note</summary><p>Entrée utile → axe I → liaison → axe II. Conclusion uniquement si demandée ou utile. Ce schéma est pédagogique, pas une obligation générale.</p></details>`,work:`${methodItemNav(4)}<h2>${r[0]}</h2><blockquote class="command-fragment">${r[1]}</blockquote>${methodField('rewrite-'+methodItem,'Reformulez en conservant les faits')}${check}`,correction:`<div class="feedback"><p>${r[2]}</p><small>${r[3]}</small></div><details><summary>Voir une note courte annotée</summary>${d.model.map(([role,text])=>`<article class="method-chip"><strong>${role}</strong><p>${text}</p></article>`).join('')}</details>`};}
 if(i===4)return {source:`<h2>Une fiche pour les agents</h2><p>Le lecteur doit pouvoir orienter les inscriptions. Quatre blocs sont imposés dans cet exercice fictif.</p>${methodDocs()}<p class="muted">Dans le sujet zéro, les quatre thèmes sont spécifiques à l’économie du livre : ne recopiez pas notre maquette sans lire la commande.</p>`,work:`<div class="support-editor">${methodSupportOrder().map((j,pos)=>{const [title]=d.support[j];return `<article class="method-chip">${methodField('support-'+j,title)}<div class="row">${btn('↑ Monter','method-support-up',`data-index="${pos}" ${pos===0?'disabled':''} aria-label="Monter le bloc ${j+1}"`)}${btn('↓ Descendre','method-support-down',`data-index="${pos}" ${pos===3?'disabled':''} aria-label="Descendre le bloc ${j+1}"`)}</div></article>`;}).join('')}</div><details><summary>Voir ma maquette</summary><div class="support-preview">${methodSupportPreview()}</div></details>${check}`,correction:`<div class="feedback"><strong>Proposition, pas modèle obligatoire</strong>${d.support.map(([t,v])=>`<h3>${t}</h3><p>${v}</p>`).join('')}</div><p>Relisez votre fiche : message principal identifiable, informations fidèles, action possible. L’outil ne certifie pas votre rédaction.</p>`};
 if(i===5){const values=methodBudget(),b=MethodRules.budget(values,d.duration);return {source:`<h2>180 minutes à répartir</h2><details open><summary>Quand quitter la lecture ?</summary><p>Quand vos axes ont les faits essentiels et leurs références, passez au plan. Ne cherchez pas à tout copier.</p></details><details><summary>Si vous prenez du retard</summary><p>Raccourcissez les détails, pas les productions obligatoires. Fixez des points de passage. Gardez une relecture et un support sobre.</p></details>`,work:`<p>Répartition indicative pour les productions du sujet zéro, à adapter au sujet réel.</p><div id="method-time-bar" class="time-ribbon">${methodTimeBar(values)}</div><div class="budget-grid">${d.budget.map(([title],j)=>`<label>${title}<input aria-label="Minutes : ${title}" type="number" min="0" max="180" step="1" data-draft="method-budget-${j}" value="${Number.isFinite(values[j])?values[j]:''}"></label>`).join('')}</div><p id="method-budget-status" role="status">${methodBudgetStatus(b)}</p>${btn('Revenir à la proposition','method-budget-reset')}`,correction:'<p>La relecture garde un créneau explicite. Une rédaction longue demande plus de temps qu’une réponse courte : adaptez aussi aux coefficients ou points indiqués par le sujet, sans inventer de barème.</p>'};}
 return {source:`<h2>Relire avec une cible</h2><p>Choisissez une carte, cherchez l’erreur correspondante dans votre production, puis retournez-la.</p><details><summary>Consignes matérielles</summary><p>Le sujet zéro demande une copie anonyme et une écriture lisible, avec encre bleue ou noire. Les couleurs de cet atelier ne sont pas destinées à être reproduites sur la copie. Relisez les instructions de votre sujet.</p></details>`,work:`<div class="review-cards">${d.checks.map(([title,q,example],j)=>btn(`<strong>${title}</strong><span>${methodFlips.has(j)?example:q}</span><small>${methodFlips.has(j)?'Revenir à la question ↶':'Voir un piège ↶'}</small>`,'method-flip',`data-index="${j}" aria-pressed="${methodFlips.has(j)}"`,'review-flip')).join('')}</div>`,correction:'<p>Une relecture ciblée est plus utile qu’une lecture rapide sans objectif. Corrigez la copie, puis vérifiez à nouveau la commande.</p>'};
}
function methodSupportOrder(){try{const order=JSON.parse(methodValue('support-order','[0,1,2,3]'));return Array.isArray(order)&&order.length===4&&new Set(order).size===4&&order.every(n=>Number.isInteger(n)&&n>=0&&n<4)?order:[0,1,2,3];}catch{return [0,1,2,3];}}
function methodSupportPreview(){return methodSupportOrder().map(j=>`<article><strong>${methodData().support[j][0]}</strong><p>${esc(methodValue('support-'+j)||'Bloc à compléter')}</p></article>`).join('');}
function methodBudget(){return methodData().budget.map(([,v],j)=>{const raw=methodValue('budget-'+j,String(v));return raw.trim()===''?NaN:Number(raw);});}
function methodTimeBar(values){return values.map((v,j)=>`<span style="flex:${Number.isFinite(v)&&v>0?v:0};${v>0?'':'display:none'}" title="${methodData().budget[j][0]} : ${v} min">${Number.isFinite(v)?v:''}</span>`).join('');}
function methodBudgetStatus(b){return b.valid?'✓ 180 minutes · relecture réservée.':b.sum?'△ Total '+b.sum+' min · '+(b.remaining>=0?b.remaining+' min à répartir':(-b.remaining)+' min à retirer')+(methodBudget()[6]<=0?' · réservez une relecture.':''):'△ Saisissez des minutes entières de 0 à 180.';}
function methodAttempt(){const i=methodStep();if(i===0)return !!methodValue('command-'+methodItem);if(i===1)return ['doc','kind','theme'].every(k=>methodValue('extract-'+k+'-'+methodItem));if(i===2)return methodData().planCards.every((_,j)=>methodValue('plan-card-'+j))&&methodValue('plan-titles').trim();if(i===3)return methodValue('rewrite-'+methodItem).trim();if(i===4)return [0,1,2,3].every(j=>methodValue('support-'+j).trim());return true;}
function methodRender(){render();$('#main').focus({preventScroll:true});}
function handleMethodAction(b){const a=b.dataset.action;if(!a.startsWith('method-'))return false;
 const reset=()=>{methodMobilePanel="work";methodCorrection=false;methodRecall=false;};
 switch(a){
 case 'method-panel':methodMobilePanel=b.dataset.panel;methodRender();break;
 case 'method-open':state.drafts['method-origin']=activeCase;save();go('method');break;
 case 'method-return':{const origin=state.drafts['method-origin'];if(C.cases.some(c=>c.id===origin))activeCase=origin;go('practice');break;}
 case 'method-mode':state.drafts['method-mode']=b.dataset.mode;save();methodRender();break;
 case 'method-step':state.drafts['method-step']=b.dataset.index;methodItem=0;reset();save();methodRender();break;
 case 'method-prev':case 'method-next':state.drafts['method-step']=String(Math.max(0,Math.min(6,methodStep()+(a==='method-next'?1:-1))));methodItem=0;reset();save();methodRender();break;
 case 'method-item-prev':case 'method-item-next':methodItem+=a==='method-item-next'?1:-1;reset();methodRender();break;
 case 'method-check':if(!methodAttempt()){$('#method-feedback').textContent='Faites une tentative dans chaque champ demandé avant de comparer.';}else{methodCorrection=true;methodMobilePanel="help";methodRender();}break;
 case 'method-recall':{const val=methodValue('recall-'+methodStep()).trim();$('#method-recall-answer').innerHTML=val?`<p class="feedback">${methodData().steps[methodStep()].answer}</p>`:'<p>Notez une tentative, même partielle, avant de vérifier.</p>';methodRecall=!!val;break;}
 case 'method-budget-reset':methodData().budget.forEach(([,v],j)=>state.drafts['method-budget-'+j]=String(v));save();methodRender();break;
 case 'method-flip':{const j=Number(b.dataset.index);methodFlips.has(j)?methodFlips.delete(j):methodFlips.add(j);methodRender();$(`[data-action="method-flip"][data-index="${j}"]`).focus({preventScroll:true});break;}
 case 'method-support-up':case 'method-support-down':{const j=Number(b.dataset.index),k=j+(a==='method-support-up'?-1:1);if(k<0||k>3)break;const order=methodSupportOrder();[order[j],order[k]]=[order[k],order[j]];state.drafts['method-support-order']=JSON.stringify(order);save();methodRender();break;}
 }
 return true;
}
function enhanceMethod(){if(view!=='practice')return;
 $('#main .page-head').insertAdjacentHTML('afterend',`<div class="row method-access">${btn('🌳 Apprendre la méthode','method-open')}<small>Commande → dossier → plan → rédaction → support → temps → relecture</small></div>`);
 document.querySelectorAll('#main .workshop-stage').forEach((stage,index)=>{const step=practiceMode==='complete'?index:practiceStep,advice=methodData().steps[Math.min(step,3)];
 stage.insertAdjacentHTML('afterbegin',`<details class="context-method"><summary>Aide méthodologique pour cette étape</summary><p>${advice.tip}</p>${btn('Ouvrir l’atelier de méthode','method-open','','link')}</details>`);
 });
}
if(typeof document!=='undefined')document.addEventListener('input',event=>{const key=event.target.dataset.draft;if(!key?.startsWith('method-'))return;state.drafts[key]=event.target.value;save();if(key.startsWith('method-support-')&&$('.support-preview'))$('.support-preview').innerHTML=methodSupportPreview();if(key.startsWith('method-budget-')){const values=methodBudget();$('#method-time-bar').innerHTML=methodTimeBar(values);$('#method-budget-status').textContent=methodBudgetStatus(MethodRules.budget(values));}});

