const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const Rules=require('../methodology-ui.js'),E=require('../engine.js');
function setup(){const c={window:{},state:E.empty(),C:{sources:{concours:{url:'official'},zeroCase:{url:'zero'}}},esc:v=>String(v??'').replaceAll('<','&lt;'),heading:()=>'',btn:(text)=>`<button>${text}</button>`};vm.createContext(c);for(const f of ['data/methodology.js','methodology-ui.js'])vm.runInContext(fs.readFileSync(f,'utf8'),c);return c;}
test('budget : 180 minutes, relecture protégée, entrées invalides refusées',()=>{const b=[10,35,15,30,50,25,15];assert.equal(Rules.budget(b).valid,true);for(const values of [[10,35,15,30,50,25,0],[10,35,15,30,50,40,0],[10,35,15,30,50,25,16],[10,35,15,30,50,25,NaN],[10,35,15,30,50,25,14.5],[]])assert.equal(Rules.budget(values).valid,false);});
test('contenu : sources de dossier cohérentes, sept étapes et modèle court',()=>{const c=setup(),d=c.window.METHOD_CONTENT;assert.equal(d.steps.length,7);assert.equal(d.command.length,6);assert.equal(d.rewrites.length,4);assert.ok(d.model.map(x=>x[1]).join(' ').split(/\s+/).length<=150);for(const e of d.extracts)assert.ok(e.doc==='Aucun'||d.documents.some(doc=>doc.id===e.doc));assert.equal(Rules.budget(Array.from(d.budget,x=>x[1])).valid,true);});
test('correction : tentative nécessaire et mode sans aide sur demande',()=>{const c=setup();assert.equal(vm.runInContext('methodAttempt()',c),false);c.state.drafts['method-command-0']='Rôle';assert.equal(vm.runInContext('methodAttempt()',c),true);assert.match(vm.runInContext('methodView()',c),/La proposition apparaît après votre tentative/);c.state.drafts['method-mode']='free';assert.match(vm.runInContext('methodView()',c),/<summary>Un indice à la demande/);c.state.drafts['method-step']='2';assert.equal(vm.runInContext('!!methodAttempt()',c),false);});
test('ordre du support : permutation persistante, titres et textes restent liés',()=>{const c=setup();c.state.drafts['method-support-order']='[3,0,1,2]';c.state.drafts['method-support-3']='Action conservée';const html=vm.runInContext('methodSupportPreview()',c);assert.ok(html.indexOf('Action conservée')<html.indexOf('Titre'));for(const bad of ['[0,0,2,3]','[0,1,2,7]','null','cassé']){c.state.drafts['method-support-order']=bad;assert.equal(vm.runInContext('JSON.stringify(methodSupportOrder())',c),'[0,1,2,3]');}});
test('sauvegarde : anciens brouillons et nouvelles réponses traversent export/import',()=>{const c=setup();c.state.drafts.plan='Ancien plan';c.state.drafts['method-rewrite-0']='Nouvelle réponse';c.state.drafts['method-support-order']='[3,0,1,2]';c.state.seconds=92;const restored=E.validate(JSON.parse(JSON.stringify(c.state)),[]);assert.deepEqual(restored.drafts,c.state.drafts);assert.equal(restored.seconds,92);assert.deepEqual(restored.progress,{});});
test('étape sauvegardée bornée, toutes les vues se rendent sans erreur',()=>{const c=setup();for(let i=0;i<7;i++){c.state.drafts['method-step']=String(i);assert.ok(vm.runInContext('methodView()',c).includes('method-desk'));}for(const [value,expected] of [['1.5',1],['bad',0],['99',6],['-3',0]]){c.state.drafts['method-step']=value;assert.equal(vm.runInContext('methodStep()',c),expected);}});
